apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/k8ssandra/cass-operator/config/deployments/cluster?ref=master

components:
  - ../../components/cass-operator-image-config
images:
- name: k8ssandra/cass-operator
  newTag: v1.19.0-dev.ff5bc87-20240111
