apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: k8ssandra
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2021-12-04T06:16:52Z"
    generation: 1
    labels:
      app: k8ssandra-dc1-stargate
      app.kubernetes.io/instance: k8ssandra
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: k8ssandra
      app.kubernetes.io/part-of: k8ssandra-k8ssandra-default
      helm.sh/chart: k8ssandra-1.5.0-SNAPSHOT
      release: k8ssandra
    name: k8ssandra-prometheus-dc1-stargate
    namespace: default
    resourceVersion: "15638"
    uid: 7488d4f6-de42-45b7-bcdc-8d7cb0f311c4
  spec:
    endpoints:
    - interval: 15s
      metricRelabelings:
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_.*
        replacement: dc1
        sourceLabels:
        - __name__
        targetLabel: dc
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_.*
        replacement: k8ssandra
        sourceLabels:
        - __name__
        targetLabel: cluster
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_.*
        replacement: default
        sourceLabels:
        - __name__
        targetLabel: rack
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_(\w+)_Read.*
        replacement: read
        sourceLabels:
        - __name__
        targetLabel: request_type
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_(\w+)_Write.*
        replacement: write
        sourceLabels:
        - __name__
        targetLabel: request_type
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_(\w+)_CASRead.*
        replacement: cas_read
        sourceLabels:
        - __name__
        targetLabel: request_type
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_(\w+)_CASWrite.*
        replacement: cas_write
        sourceLabels:
        - __name__
        targetLabel: request_type
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_(\w+)_RangeSlice.*
        replacement: range_slice
        sourceLabels:
        - __name__
        targetLabel: request_type
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_(\w+)_ViewWrite.*
        replacement: view_write
        sourceLabels:
        - __name__
        targetLabel: request_type
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_Latency_(Read|Write|CASRead|CASWrite|RangeSlice|ViewWrite)_count
        replacement: stargate_client_request_latency_total
        sourceLabels:
        - __name__
        targetLabel: __name__
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_Latency_(Read|Write|CASRead|CASWrite|RangeSlice|ViewWrite)
        replacement: stargate_client_request_latency_quantile
        sourceLabels:
        - __name__
        targetLabel: __name__
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_Failures_(Read|Write|CASRead|CASWrite|RangeSlice|ViewWrite)_total
        replacement: stargate_client_request_failures_total
        sourceLabels:
        - __name__
        targetLabel: __name__
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_Timeouts_(Read|Write|CASRead|CASWrite|RangeSlice|ViewWrite)_total
        replacement: stargate_client_request_timeouts_total
        sourceLabels:
        - __name__
        targetLabel: __name__
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_Unavailables_(Read|Write|CASRead|CASWrite|RangeSlice|ViewWrite)_total
        replacement: stargate_client_request_unavailables_total
        sourceLabels:
        - __name__
        targetLabel: __name__
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_ConditionNotMet_(Read|Write|CASRead|CASWrite|RangeSlice|ViewWrite)
        replacement: stargate_client_request_condition_not_met_total
        sourceLabels:
        - __name__
        targetLabel: __name__
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_UnfinishedCommit_(Read|Write|CASRead|CASWrite|RangeSlice|ViewWrite)
        replacement: stargate_client_request_unfinished_commit_total
        sourceLabels:
        - __name__
        targetLabel: __name__
      - regex: persistence_cassandra_(\d_\d+)_org_apache_cassandra_metrics_ClientRequest_ContentionHistogram_(Read|Write|CASRead|CASWrite|RangeSlice|ViewWrite)_count
        replacement: stargate_client_request_contention_histogran_total
        sourceLabels:
        - __name__
        targetLabel: __name__
      path: /metrics
      port: health
      scheme: http
      scrapeTimeout: 15s
    namespaceSelector:
      matchNames:
      - default
    selector:
      matchLabels:
        app: k8ssandra-dc1-stargate
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: k8ssandra
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2021-12-04T06:16:52Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: k8ssandra
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: k8ssandra
      app.kubernetes.io/part-of: k8ssandra-k8ssandra-default
      helm.sh/chart: k8ssandra-1.5.0-SNAPSHOT
      release: k8ssandra
    name: k8ssandra-prometheus-k8ssandra
    namespace: default
    resourceVersion: "15639"
    uid: 6cfff0c6-b054-41ac-833d-644111ca975c
  spec:
    endpoints:
    - interval: 15s
      metricRelabelings:
      - regex: collectd_mcac_(meter|histogram).*
        replacement: ${1}
        sourceLabels:
        - __name__
        targetLabel: kind
      - action: drop
        regex: .*rate_(mean|1m|5m|15m)
        sourceLabels:
        - __name__
      - regex: (collectd_mcac_.+)
        replacement: ${1}
        sourceLabels:
        - __name__
        targetLabel: prom_name
      - regex: .+_bucket_(\d+)
        replacement: ${1}
        sourceLabels:
        - prom_name
        targetLabel: le
      - regex: .+_bucket_inf
        replacement: +Inf
        sourceLabels:
        - prom_name
        targetLabel: le
      - regex: .*_histogram_p(\d+)
        replacement: .${1}
        sourceLabels:
        - prom_name
        targetLabel: quantile
      - regex: .*_histogram_min
        replacement: "0"
        sourceLabels:
        - prom_name
        targetLabel: quantile
      - regex: .*_histogram_max
        replacement: "1"
        sourceLabels:
        - prom_name
        targetLabel: quantile
      - action: drop
        regex: org\.apache\.cassandra\.metrics\.table\.(\w+)
        sourceLabels:
        - mcac
      - regex: org\.apache\.cassandra\.metrics\.table\.(\w+)\.(\w+)\.(\w+)
        replacement: ${3}
        sourceLabels:
        - mcac
        targetLabel: table
      - regex: org\.apache\.cassandra\.metrics\.table\.(\w+)\.(\w+)\.(\w+)
        replacement: ${2}
        sourceLabels:
        - mcac
        targetLabel: keyspace
      - regex: org\.apache\.cassandra\.metrics\.table\.(\w+)\.(\w+)\.(\w+)
        replacement: mcac_table_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.keyspace\.(\w+)\.(\w+)
        replacement: ${2}
        sourceLabels:
        - mcac
        targetLabel: keyspace
      - regex: org\.apache\.cassandra\.metrics\.keyspace\.(\w+)\.(\w+)
        replacement: mcac_keyspace_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.thread_pools\.(\w+)\.(\w+)\.(\w+).*
        replacement: ${2}
        sourceLabels:
        - mcac
        targetLabel: pool_type
      - regex: org\.apache\.cassandra\.metrics\.thread_pools\.(\w+)\.(\w+)\.(\w+).*
        replacement: ${3}
        sourceLabels:
        - mcac
        targetLabel: pool_name
      - regex: org\.apache\.cassandra\.metrics\.thread_pools\.(\w+)\.(\w+)\.(\w+).*
        replacement: mcac_thread_pools_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.client_request\.(\w+)\.(\w+)$
        replacement: ${2}
        sourceLabels:
        - mcac
        targetLabel: request_type
      - regex: org\.apache\.cassandra\.metrics\.client_request\.(\w+)\.(\w+)$
        replacement: mcac_client_request_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.client_request\.(\w+)\.(\w+)\.(\w+)$
        replacement: ${3}
        sourceLabels:
        - mcac
        targetLabel: cl
      - regex: org\.apache\.cassandra\.metrics\.client_request\.(\w+)\.(\w+)\.(\w+)$
        replacement: ${2}
        sourceLabels:
        - mcac
        targetLabel: request_type
      - regex: org\.apache\.cassandra\.metrics\.client_request\.(\w+)\.(\w+)\.(\w+)$
        replacement: mcac_client_request_${1}_cl
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.cache\.(\w+)\.(\w+)
        replacement: ${2}
        sourceLabels:
        - mcac
        targetLabel: cache_name
      - regex: org\.apache\.cassandra\.metrics\.cache\.(\w+)\.(\w+)
        replacement: mcac_cache_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.cql\.(\w+)
        replacement: mcac_cql_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.dropped_message\.(\w+)\.(\w+)
        replacement: ${2}
        sourceLabels:
        - mcac
        targetLabel: message_type
      - regex: org\.apache\.cassandra\.metrics\.dropped_message\.(\w+)\.(\w+)
        replacement: mcac_dropped_message_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.streaming\.(\w+)\.(.+)$
        replacement: ${2}
        sourceLabels:
        - mcac
        targetLabel: peer_ip
      - regex: org\.apache\.cassandra\.metrics\.streaming\.(\w+)\.(.+)$
        replacement: mcac_streaming_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.streaming\.(\w+)$
        replacement: mcac_streaming_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.commit_log\.(\w+)
        replacement: mcac_commit_log_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.compaction\.(\w+)
        replacement: mcac_compaction_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.storage\.(\w+)
        replacement: mcac_storage_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.batch\.(\w+)
        replacement: mcac_batch_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.client\.(\w+)
        replacement: mcac_client_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.buffer_pool\.(\w+)
        replacement: mcac_buffer_pool_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.index\.(\w+)
        replacement: mcac_sstable_index_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.hinted_hand_off_manager\.([^\-]+)-(\w+)
        replacement: ${2}
        sourceLabels:
        - mcac
        targetLabel: peer_ip
      - regex: org\.apache\.cassandra\.metrics\.hinted_hand_off_manager\.([^\-]+)-(\w+)
        replacement: mcac_hints_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.hints_service\.hints_delays\-(\w+)
        replacement: ${1}
        sourceLabels:
        - mcac
        targetLabel: peer_ip
      - regex: org\.apache\.cassandra\.metrics\.hints_service\.hints_delays\-(\w+)
        replacement: mcac_hints_hints_delays
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.hints_service\.([^\-]+)
        replacement: mcac_hints_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.memtable_pool\.(\w+)
        replacement: mcac_memtable_pool_${1}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: com\.datastax\.bdp\.type\.performance_objects\.name\.cql_slow_log\.metrics\.queries_latency
        replacement: mcac_cql_slow_log_query_latency
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: org\.apache\.cassandra\.metrics\.read_coordination\.(.*)
        replacement: $1
        sourceLabels:
        - mcac
        targetLabel: read_type
      - regex: jvm\.gc\.(\w+)\.(\w+)
        replacement: ${1}
        sourceLabels:
        - mcac
        targetLabel: collector_type
      - regex: jvm\.gc\.(\w+)\.(\w+)
        replacement: mcac_jvm_gc_${2}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: jvm\.memory\.(\w+)\.(\w+)
        replacement: ${1}
        sourceLabels:
        - mcac
        targetLabel: memory_type
      - regex: jvm\.memory\.(\w+)\.(\w+)
        replacement: mcac_jvm_memory_${2}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: jvm\.memory\.pools\.(\w+)\.(\w+)
        replacement: ${2}
        sourceLabels:
        - mcac
        targetLabel: pool_name
      - regex: jvm\.memory\.pools\.(\w+)\.(\w+)
        replacement: mcac_jvm_memory_pool_${2}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: jvm\.fd\.usage
        replacement: mcac_jvm_fd_usage
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: jvm\.buffers\.(\w+)\.(\w+)
        replacement: ${1}
        sourceLabels:
        - mcac
        targetLabel: buffer_type
      - regex: jvm\.buffers\.(\w+)\.(\w+)
        replacement: mcac_jvm_buffer_${2}
        sourceLabels:
        - mcac
        targetLabel: __name__
      - regex: (mcac_.*);.*(_micros_bucket|_bucket|_micros_count_total|_count_total|_total|_micros_sum|_sum|_stddev).*
        replacement: ${1}${2}
        separator: ;
        sourceLabels:
        - __name__
        - prom_name
        targetLabel: __name__
      - action: labeldrop
        regex: prom_name
      path: /metrics
      port: prometheus
      scheme: http
      scrapeTimeout: 15s
      targetPort: 9103
    namespaceSelector:
      matchNames:
      - default
    selector:
      matchExpressions:
      - key: cassandra.datastax.com/cluster
        operator: In
        values:
        - k8ssandra
      - key: cassandra.datastax.com/datacenter
        operator: In
        values:
        - dc1
      matchLabels:
        app.kubernetes.io/managed-by: cass-operator
        cassandra.datastax.com/prom-metrics: "true"
    targetLabels:
    - cassandra.datastax.com/cluster
    - cassandra.datastax.com/datacenter
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
